var Notice = 
{
	'FD0000': '안내문구 Test 입니다.<br>' +
	          '<font color=blue>색상</font>도 입힐 수 있습니다.<br>' + 
			  '문자가 길면 자동으로 아래로 옮겨지네요 ^^~~~~~~~~~~~~~~~~~~~~~~~<br>' +
			  '라인이 많으면 스크롤이 보이진 않지만 아래로 옮겨집니다.<br>' +
			  'theApp.alert의 최대 크기가 정해져 있습니다.<br>' +
			  '1<br>' +
			  '2<br>' +
			  '3<br>' +
			  '4<br>' +
			  '5<br>' +
			  '6<br>' +
			  '7<br>' +
			  '8<br>' +
			  '9<br>' +
			  '0<br>' +
			  '1<br>' +
			  '2<br>' +
			  '3<br>' +
			  '4<br>' +
			  '5<br>' +
			  '6<br>' +
			  '7<br>' +
			  '8<br>' +
			  '9<br>' +
			  '0<br>' +
			  '1<br>' +
			  '2<br>' +
			  '3<br>' +
			  '4<br>' +
			  '5<br>' +
			  '6<br>' +
			  '7<br>' +
			  '8<br>' +
			  '9',

	'FD0001':	[
					['Test1',	'안내문구 Test 입니다.<br>' +
	          					'<font color=blue>색상</font>도 입힐 수 있습니다.<br>' +
								'문자가 길면 자동으로 아래로 옮겨지네요 ^^~~~~~~~~~~~~~~~~~~~~~~~' +
			  					'라인이 많으면 스크롤이 보이진 않지만 아래로 옮겨집니다.' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9<br>' +
								'0<br>' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9'],
					['Test2',	'문자가 길면 자동으로 아래로 옮겨지네요 ^^~~~~~~~~~~~~~~~~~~~~~~~<br>' +
			  					'라인이 많으면 스크롤이 보이진 않지만 아래로 옮겨집니다.'],
					['Test3',	'안내문구 Test 입니다.' +
	          					'<font color=blue>색상</font>도 입힐 수 있습니다.<br>' +
								'문자가 길면 자동으로 아래로 옮겨지네요 ^^~~~~~~~~~~~~~~~~~~~~~~~' +
			  					'라인이 많으면 스크롤이 보이진 않지만 아래로 옮겨집니다.' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9<br>' +
								'0<br>' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9'],
					['Test4',	'안내문구 Test 입니다.' +
	          					'<font color=blue>색상</font>도 입힐 수 있습니다.<br>' +
								'문자가 길면 자동으로 아래로 옮겨지네요 ^^~~~~~~~~~~~~~~~~~~~~~~~' +
			  					'라인이 많으면 스크롤이 보이진 않지만 아래로 옮겨집니다.' +
								'1<br>' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9<br>' +
								'0<br>' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9']
				],
	'FD1302':	
					'고객님의 중요 거래내용이 통지되므로,<br>' +
					'안전한 금융거래와 고객님의 소중한 정보보호를 위하여 주소·EMAIL·휴대전화번호 등을 정확히 입력해주시기 바랍니다.'
				,
	'FD1402':	[
					['Test1',	'안내문구 Test 입니다.<br>' +
	          					'<font color=blue>색상</font>도 입힐 수 있습니다.<br>' +
								'문자가 길면 자동으로 아래로 옮겨지네요 ^^~~~~~~~~~~~~~~~~~~~~~~~' +
			  					'라인이 많으면 스크롤이 보이진 않지만 아래로 옮겨집니다.' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9<br>' +
								'0<br>' +
								'1<br>' +
								'2<br>' +
								'3<br>' +
								'4<br>' +
								'5<br>' +
								'6<br>' +
								'7<br>' +
								'8<br>' +
								'9']
				],
	'FD3102': [
					['Test1','- 이 금융투자상품은 예금자보호법에 따라 예금보험공사가 보호하지 않으며, 투자원금의 손실이 발생할 수 있고, 이는 투자자에게 귀속됩니다.<br>' +
	          					'- 당사는 금융투자상품에 대하여 충분히 설명할 의무가 있으며, 투자자는 투자에 앞서 그러한 설명을 충분히 설명할 의무가 있으며, 투자자는 투자에 앞서 그러한 설명을 충분히 들으시기 바랍니다.<br>' +
								'- 가입 전에 투자대상, 환매방법, 보수 및 수수료 등에 관하여 (간이)투자설명서 및 투자계약권유문서를 반드시 읽어보시기 바랍니다.<br>' +
			  					'- 외화자산은 활율변동에 따라 자산가치가 변동되거나 원금손실이 발생할 수 있습니다.<br>' +
								'- 펀드의 수익이 없거나 손실이 나는 경우에도 이자 및 배당 등 과세 소득에 대해 세금이 부과될 수 있습니다.<br>' +
								'- 과거 운용성과가 미래의 수익을 보장하지는 않습니다.<br>' +
								'- 당일 기준가는 08:30분 이후 갱신됩니다.<br>' ]
					],
	'FD1402_mini':	'문자가 길면 자동으로 아래로 옮겨지네요<br>' +
					'^^~~~~~~~~~~~~~~~~~~~~~~~<br>' +
					'라인이 많으면 스크롤이 보이진 않지만 아래로 옮겨집니다.'
};

//or Notice['10000']; or Message.Hello;
Notice.getNotice = function(code)
{
	var msg = Notice[code];
	
	if(msg) return msg;
	else return 'no Notice';
};

// 안내문구 팝업창 호출
Notice.openNoticeWindow = function(opener, pageId, width, height)
{
	var win = AWindow.createWindow('FD/window/FD0000_W03.lay','FD000003');	
	
	win.opener = opener;
	
	win.setNotice(Notice.getNotice(pageId));
	
	win.setWindowOption(
	{
		isModal: true,
		isAutoCenter: true,
		modalBgOption: 'dark'
	});
	
	win.open(opener, 0, 0, width, height);
};

Notice.openNoticeMiniWindow = function(opener, pageId, width, height, text, left, top)
{
	var win = AWindow.createWindow('FD/window/FD0000_W04.lay','FD000004');
	
	win.opener = opener;
	
	if (text)
	{
		win.setNotice(text);
	}
	else
	{
		win.setNotice(Notice.getNotice(pageId));
	}
	
	win.setWindowOption(
	{
		isModal:true,
		isAutoCenter: false,	//자동 중앙정렬
		isFocusLostClose: true,	//모달인 경우 포커스를 잃을 때 창을 닫을지
		modalBgOption: 'none'	//none, light, dark 모달인 경우 배경색상
	});

	win.open(opener, 0, 0, width, height);
	
	if (left || top)
	{
		win.setPos({left:left, top:top});
	}
};
